export * from "./loginPage/LoginPage"
export * from "./photos/Photos"
export * from "./recycleBin/RecycleBin"
export * from "./sharedFiles/SharedFiles"
export * from "./mainContent/MainContent"
export * from "./mainPage/MainPage"
export * from ".//registrationPage/RegistrationPage"